apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopacker
  namespace: gopacker
spec:
  selector:
    matchLabels:
      app: gopacker
  template:
    metadata:
      labels:
        app: gopacker
    spec:
      containers:
      - name: gopacker
        image: monomo/gopacker:1.0
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gopacker
  namespace: gopacker
spec:
  selector:
    app: gopacker
  ports:
  - port: 80
    targetPort: 80
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: gopacker
  labels:
    app: gopacker
  namespace: gopacker
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - gopacker.monomo.network
      secretName: gopackertls
  rules:
    - host: gopacker.monomo.network
      http:
        paths:
          - backend:
              serviceName: gopacker
              servicePort: 80
